"""
База сайтов для поиска по нику (1000+ сайтов)
"""

SITES = [
    # === СОЦИАЛЬНЫЕ СЕТИ ===
    {"name": "VK", "uri_check": "https://vk.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://vk.com/{username}"},
    {"name": "Facebook", "uri_check": "https://www.facebook.com/{username}", "m_string": "Content Not Found", "cat": "social", "uri_pretty": "https://www.facebook.com/{username}"},
    {"name": "Instagram", "uri_check": "https://www.instagram.com/{username}/", "m_string": "Page Not Found", "cat": "social", "uri_pretty": "https://www.instagram.com/{username}/"},
    {"name": "Twitter", "uri_check": "https://twitter.com/{username}", "m_string": "This account doesn't exist", "cat": "social", "uri_pretty": "https://twitter.com/{username}"},
    {"name": "TikTok", "uri_check": "https://www.tiktok.com/@{username}", "m_string": "Couldn't find this account", "cat": "social", "uri_pretty": "https://www.tiktok.com/@{username}"},
    {"name": "Snapchat", "uri_check": "https://www.snapchat.com/add/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.snapchat.com/add/{username}"},
    {"name": "Pinterest", "uri_check": "https://www.pinterest.com/{username}/", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.pinterest.com/{username}/"},
    {"name": "LinkedIn", "uri_check": "https://www.linkedin.com/in/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.linkedin.com/in/{username}"},
    {"name": "Reddit", "uri_check": "https://www.reddit.com/user/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.reddit.com/user/{username}"},
    {"name": "Tumblr", "uri_check": "https://{username}.tumblr.com/", "m_string": "Not Found", "cat": "social", "uri_pretty": "https://{username}.tumblr.com/"},
    {"name": "Mastodon", "uri_check": "https://mastodon.social/@{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://mastodon.social/@{username}"},
    {"name": "Threads", "uri_check": "https://www.threads.net/@{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.threads.net/@{username}"},
    {"name": "Bluesky", "uri_check": "https://bsky.app/profile/{username}.bsky.social", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://bsky.app/profile/{username}.bsky.social"},
    {"name": "TruthSocial", "uri_check": "https://truthsocial.com/@{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://truthsocial.com/@{username}"},
    {"name": "Gab", "uri_check": "https://gab.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://gab.com/{username}"},
    {"name": "Minds", "uri_check": "https://www.minds.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.minds.com/{username}"},
    {"name": "MeWe", "uri_check": "https://mewe.com/i/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://mewe.com/i/{username}"},
    {"name": "Parler", "uri_check": "https://parler.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://parler.com/{username}"},
    {"name": "Vero", "uri_check": "https://vero.co/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://vero.co/{username}"},
    {"name": "Ello", "uri_check": "https://ello.co/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://ello.co/{username}"},
    {"name": "About.me", "uri_check": "https://about.me/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://about.me/{username}"},
    {"name": "Linktree", "uri_check": "https://linktr.ee/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://linktr.ee/{username}"},
    {"name": "Carrd", "uri_check": "https://{username}.carrd.co", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://{username}.carrd.co"},
    {"name": "Gravatar", "uri_check": "https://en.gravatar.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://en.gravatar.com/{username}"},
    {"name": "Disqus", "uri_check": "https://disqus.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://disqus.com/{username}"},
    
    # === МЕССЕНДЖЕРЫ ===
    {"name": "Telegram", "uri_check": "https://t.me/{username}", "m_string": "not found", "cat": "messaging", "uri_pretty": "https://t.me/{username}"},
    {"name": "WhatsApp", "uri_check": "https://wa.me/{username}", "m_string": "Page not found", "cat": "messaging", "uri_pretty": "https://wa.me/{username}"},
    {"name": "Viber", "uri_check": "https://viber.com/{username}", "m_string": "Page not found", "cat": "messaging", "uri_pretty": "https://viber.com/{username}"},
    {"name": "Signal", "uri_check": "https://signal.org/{username}", "m_string": "Page not found", "cat": "messaging", "uri_pretty": "https://signal.org/{username}"},
    {"name": "Discord", "uri_check": "https://discord.com/users/{username}", "m_string": "Page not found", "cat": "messaging", "uri_pretty": "https://discord.com/users/{username}"},
    {"name": "Skype", "uri_check": "https://join.skype.com/{username}", "m_string": "Page not found", "cat": "messaging", "uri_pretty": "https://join.skype.com/{username}"},
    {"name": "WeChat", "uri_check": "https://www.wechat.com/{username}", "m_string": "Page not found", "cat": "messaging", "uri_pretty": "https://www.wechat.com/{username}"},
    {"name": "Line", "uri_check": "https://line.me/{username}", "m_string": "Page not found", "cat": "messaging", "uri_pretty": "https://line.me/{username}"},
    {"name": "KakaoTalk", "uri_check": "https://open.kakao.com/{username}", "m_string": "Page not found", "cat": "messaging", "uri_pretty": "https://open.kakao.com/{username}"},
    {"name": "Slack", "uri_check": "https://{username}.slack.com", "m_string": "Page not found", "cat": "messaging", "uri_pretty": "https://{username}.slack.com"},
    
    # === ВИДЕО ПЛАТФОРМЫ ===
    {"name": "YouTube", "uri_check": "https://www.youtube.com/@{username}", "m_string": "This channel doesn't exist", "cat": "video", "uri_pretty": "https://www.youtube.com/@{username}"},
    {"name": "Twitch", "uri_check": "https://www.twitch.tv/{username}", "m_string": "Channel does not exist", "cat": "video", "uri_pretty": "https://www.twitch.tv/{username}"},
    {"name": "Vimeo", "uri_check": "https://vimeo.com/{username}", "m_string": "Page not found", "cat": "video", "uri_pretty": "https://vimeo.com/{username}"},
    {"name": "Dailymotion", "uri_check": "https://www.dailymotion.com/{username}", "m_string": "Page not found", "cat": "video", "uri_pretty": "https://www.dailymotion.com/{username}"},
    {"name": "Rumble", "uri_check": "https://rumble.com/user/{username}", "m_string": "Page not found", "cat": "video", "uri_pretty": "https://rumble.com/user/{username}"},
    {"name": "Bitchute", "uri_check": "https://www.bitchute.com/channel/{username}", "m_string": "Page not found", "cat": "video", "uri_pretty": "https://www.bitchute.com/channel/{username}"},
    {"name": "Odysee", "uri_check": "https://odysee.com/@{username}", "m_string": "Page not found", "cat": "video", "uri_pretty": "https://odysee.com/@{username}"},
    {"name": "LiveLeak", "uri_check": "https://www.liveleak.com/c/{username}", "m_string": "Page not found", "cat": "video", "uri_pretty": "https://www.liveleak.com/c/{username}"},
    {"name": "Metacafe", "uri_check": "https://www.metacafe.com/members/{username}", "m_string": "Page not found", "cat": "video", "uri_pretty": "https://www.metacafe.com/members/{username}"},
    {"name": "Veoh", "uri_check": "https://www.veoh.com/users/{username}", "m_string": "Page not found", "cat": "video", "uri_pretty": "https://www.veoh.com/users/{username}"},
    
    # === ФОТО ХОСТИНГИ ===
    {"name": "Flickr", "uri_check": "https://www.flickr.com/people/{username}", "m_string": "Page not found", "cat": "photo", "uri_pretty": "https://www.flickr.com/people/{username}"},
    {"name": "500px", "uri_check": "https://500px.com/p/{username}", "m_string": "Page not found", "cat": "photo", "uri_pretty": "https://500px.com/p/{username}"},
    {"name": "Unsplash", "uri_check": "https://unsplash.com/@{username}", "m_string": "Page not found", "cat": "photo", "uri_pretty": "https://unsplash.com/@{username}"},
    {"name": "Pexels", "uri_check": "https://www.pexels.com/@{username}", "m_string": "Page not found", "cat": "photo", "uri_pretty": "https://www.pexels.com/@{username}"},
    {"name": "Pixabay", "uri_check": "https://pixabay.com/users/{username}", "m_string": "Page not found", "cat": "photo", "uri_pretty": "https://pixabay.com/users/{username}"},
    {"name": "DeviantArt", "uri_check": "https://www.deviantart.com/{username}", "m_string": "Page not found", "cat": "photo", "uri_pretty": "https://www.deviantart.com/{username}"},
    {"name": "ArtStation", "uri_check": "https://www.artstation.com/{username}", "m_string": "Page not found", "cat": "photo", "uri_pretty": "https://www.artstation.com/{username}"},
    {"name": "Behance", "uri_check": "https://www.behance.net/{username}", "m_string": "Page not found", "cat": "photo", "uri_pretty": "https://www.behance.net/{username}"},
    {"name": "Dribbble", "uri_check": "https://dribbble.com/{username}", "m_string": "Page not found", "cat": "photo", "uri_pretty": "https://dribbble.com/{username}"},
    {"name": "EyeEm", "uri_check": "https://www.eyeem.com/u/{username}", "m_string": "Page not found", "cat": "photo", "uri_pretty": "https://www.eyeem.com/u/{username}"},
    {"name": "SmugMug", "uri_check": "https://{username}.smugmug.com", "m_string": "Page not found", "cat": "photo", "uri_pretty": "https://{username}.smugmug.com"},
    {"name": "Imgur", "uri_check": "https://imgur.com/user/{username}", "m_string": "Page not found", "cat": "photo", "uri_pretty": "https://imgur.com/user/{username}"},
    {"name": "Photobucket", "uri_check": "https://photobucket.com/user/{username}/library", "m_string": "Page not found", "cat": "photo", "uri_pretty": "https://photobucket.com/user/{username}/library"},
    
    # === ПРОГРАММИРОВАНИЕ ===
    {"name": "GitHub", "uri_check": "https://github.com/{username}", "m_string": "Not Found", "cat": "coding", "uri_pretty": "https://github.com/{username}"},
    {"name": "GitLab", "uri_check": "https://gitlab.com/{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://gitlab.com/{username}"},
    {"name": "Bitbucket", "uri_check": "https://bitbucket.org/{username}/", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://bitbucket.org/{username}/"},
    {"name": "SourceForge", "uri_check": "https://sourceforge.net/u/{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://sourceforge.net/u/{username}"},
    {"name": "CodePen", "uri_check": "https://codepen.io/{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://codepen.io/{username}"},
    {"name": "Replit", "uri_check": "https://replit.com/@{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://replit.com/@{username}"},
    {"name": "StackOverflow", "uri_check": "https://stackoverflow.com/users/{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://stackoverflow.com/users/{username}"},
    {"name": "HackerRank", "uri_check": "https://www.hackerrank.com/{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://www.hackerrank.com/{username}"},
    {"name": "LeetCode", "uri_check": "https://leetcode.com/{username}/", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://leetcode.com/{username}/"},
    {"name": "Codeforces", "uri_check": "https://codeforces.com/profile/{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://codeforces.com/profile/{username}"},
    {"name": "HackerOne", "uri_check": "https://hackerone.com/{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://hackerone.com/{username}"},
    {"name": "Bugcrowd", "uri_check": "https://bugcrowd.com/{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://bugcrowd.com/{username}"},
    {"name": "Dev.to", "uri_check": "https://dev.to/{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://dev.to/{username}"},
    {"name": "Hashnode", "uri_check": "https://{username}.hashnode.dev", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://{username}.hashnode.dev"},
    {"name": "Medium", "uri_check": "https://medium.com/@{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://medium.com/@{username}"},
    {"name": "Keybase", "uri_check": "https://keybase.io/{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://keybase.io/{username}"},
    {"name": "DockerHub", "uri_check": "https://hub.docker.com/u/{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://hub.docker.com/u/{username}"},
    {"name": "PyPI", "uri_check": "https://pypi.org/user/{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://pypi.org/user/{username}"},
    {"name": "NPM", "uri_check": "https://www.npmjs.com/~{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://www.npmjs.com/~{username}"},
    {"name": "RubyGems", "uri_check": "https://rubygems.org/profiles/{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://rubygems.org/profiles/{username}"},
    {"name": "Packagist", "uri_check": "https://packagist.org/packages/{username}/", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://packagist.org/packages/{username}/"},
    {"name": "Maven", "uri_check": "https://mvnrepository.com/artifact/{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://mvnrepository.com/artifact/{username}"},
    {"name": "Codeberg", "uri_check": "https://codeberg.org/{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://codeberg.org/{username}"},
    {"name": "Gitea", "uri_check": "https://gitea.com/{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://gitea.com/{username}"},
    {"name": "Launchpad", "uri_check": "https://launchpad.net/~{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://launchpad.net/~{username}"},
    {"name": "SourceHut", "uri_check": "https://sr.ht/~{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://sr.ht/~{username}"},
    
    # === ИГРЫ ===
    {"name": "Steam", "uri_check": "https://steamcommunity.com/id/{username}", "m_string": "Profile not found", "cat": "gaming", "uri_pretty": "https://steamcommunity.com/id/{username}"},
    {"name": "EpicGames", "uri_check": "https://www.epicgames.com/id/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://www.epicgames.com/id/{username}"},
    {"name": "GOG", "uri_check": "https://www.gog.com/u/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://www.gog.com/u/{username}"},
    {"name": "Origin", "uri_check": "https://www.origin.com/profile/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://www.origin.com/profile/{username}"},
    {"name": "Uplay", "uri_check": "https://uplay.ubisoft.com/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://uplay.ubisoft.com/{username}"},
    {"name": "Battle.net", "uri_check": "https://battle.net/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://battle.net/{username}"},
    {"name": "Xbox", "uri_check": "https://xboxgamertag.com/search/{username}", "m_string": "No results found", "cat": "gaming", "uri_pretty": "https://xboxgamertag.com/search/{username}"},
    {"name": "PlayStation", "uri_check": "https://psnprofiles.com/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://psnprofiles.com/{username}"},
    {"name": "Nintendo", "uri_check": "https://switchfriends.com/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://switchfriends.com/{username}"},
    {"name": "Roblox", "uri_check": "https://www.roblox.com/user.aspx?username={username}", "m_string": "Page cannot be found", "cat": "gaming", "uri_pretty": "https://www.roblox.com/user.aspx?username={username}"},
    {"name": "Minecraft", "uri_check": "https://namemc.com/profile/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://namemc.com/profile/{username}"},
    {"name": "Chess.com", "uri_check": "https://www.chess.com/member/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://www.chess.com/member/{username}"},
    {"name": "Lichess", "uri_check": "https://lichess.org/@/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://lichess.org/@/{username}"},
    {"name": "FaceIT", "uri_check": "https://www.faceit.com/en/players/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://www.faceit.com/en/players/{username}"},
    {"name": "ESL", "uri_check": "https://www.eslgaming.com/player/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://www.eslgaming.com/player/{username}"},
    {"name": "Battlefy", "uri_check": "https://battlefy.com/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://battlefy.com/{username}"},
    {"name": "Challonge", "uri_check": "https://challonge.com/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://challonge.com/{username}"},
    {"name": "Smash.gg", "uri_check": "https://www.smash.gg/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://www.smash.gg/{username}"},
    {"name": "NameMC", "uri_check": "https://namemc.com/minecraft-skins/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://namemc.com/minecraft-skins/{username}"},
    {"name": "PlanetMinecraft", "uri_check": "https://www.planetminecraft.com/member/{username}/", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://www.planetminecraft.com/member/{username}/"},
    {"name": "CurseForge", "uri_check": "https://www.curseforge.com/members/{username}/projects", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://www.curseforge.com/members/{username}/projects"},
    {"name": "ModDB", "uri_check": "https://www.moddb.com/members/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://www.moddb.com/members/{username}"},
    {"name": "NexusMods", "uri_check": "https://www.nexusmods.com/users/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://www.nexusmods.com/users/{username}"},
    {"name": "SteamDB", "uri_check": "https://steamdb.info/calculator/{username}/", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://steamdb.info/calculator/{username}/"},
    {"name": "SteamRep", "uri_check": "https://steamrep.com/search?q={username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://steamrep.com/search?q={username}"},
    {"name": "Hypixel", "uri_check": "https://plancke.io/hypixel/player/name/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://plancke.io/hypixel/player/name/{username}"},
    {"name": "FortniteTracker", "uri_check": "https://fortnitetracker.com/profile/all/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://fortnitetracker.com/profile/all/{username}"},
    {"name": "ValorantTracker", "uri_check": "https://valorant.tracker.gg/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://valorant.tracker.gg/{username}"},
    {"name": "ApexTracker", "uri_check": "https://apex.tracker.gg/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://apex.tracker.gg/{username}"},
    {"name": "CodTracker", "uri_check": "https://cod.tracker.gg/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://cod.tracker.gg/{username}"},
    
    # === МУЗЫКА ===
    {"name": "Spotify", "uri_check": "https://open.spotify.com/user/{username}", "m_string": "Page not found", "cat": "music", "uri_pretty": "https://open.spotify.com/user/{username}"},
    {"name": "SoundCloud", "uri_check": "https://soundcloud.com/{username}", "m_string": "Page not found", "cat": "music", "uri_pretty": "https://soundcloud.com/{username}"},
    {"name": "Last.fm", "uri_check": "https://www.last.fm/user/{username}", "m_string": "This profile is not available", "cat": "music", "uri_pretty": "https://www.last.fm/user/{username}"},
    {"name": "Bandcamp", "uri_check": "https://bandcamp.com/{username}", "m_string": "Page not found", "cat": "music", "uri_pretty": "https://bandcamp.com/{username}"},
    {"name": "Mixcloud", "uri_check": "https://www.mixcloud.com/{username}/", "m_string": "Page not found", "cat": "music", "uri_pretty": "https://www.mixcloud.com/{username}/"},
    {"name": "ReverbNation", "uri_check": "https://www.reverbnation.com/{username}", "m_string": "Page not found", "cat": "music", "uri_pretty": "https://www.reverbnation.com/{username}"},
    {"name": "Audiomack", "uri_check": "https://audiomack.com/{username}", "m_string": "Page not found", "cat": "music", "uri_pretty": "https://audiomack.com/{username}"},
    {"name": "Tidal", "uri_check": "https://tidal.com/{username}", "m_string": "Page not found", "cat": "music", "uri_pretty": "https://tidal.com/{username}"},
    {"name": "Deezer", "uri_check": "https://www.deezer.com/profile/{username}", "m_string": "Page not found", "cat": "music", "uri_pretty": "https://www.deezer.com/profile/{username}"},
    {"name": "AppleMusic", "uri_check": "https://music.apple.com/profile/{username}", "m_string": "Page not found", "cat": "music", "uri_pretty": "https://music.apple.com/profile/{username}"},
    
    # === БЛОГИ ===
    {"name": "WordPress", "uri_check": "https://{username}.wordpress.com/", "m_string": "The site you were looking for couldn't be found", "cat": "blog", "uri_pretty": "https://{username}.wordpress.com/"},
    {"name": "Blogger", "uri_check": "https://{username}.blogspot.com/", "m_string": "Page not found", "cat": "blog", "uri_pretty": "https://{username}.blogspot.com/"},
    {"name": "LiveJournal", "uri_check": "https://{username}.livejournal.com/", "m_string": "Page not found", "cat": "blog", "uri_pretty": "https://{username}.livejournal.com/"},
    {"name": "Blogger", "uri_check": "https://www.blogger.com/profile/{username}", "m_string": "Page not found", "cat": "blog", "uri_pretty": "https://www.blogger.com/profile/{username}"},
    {"name": "Wix", "uri_check": "https://{username}.wixsite.com", "m_string": "Page not found", "cat": "blog", "uri_pretty": "https://{username}.wixsite.com"},
    {"name": "Weebly", "uri_check": "https://{username}.weebly.com", "m_string": "Page not found", "cat": "blog", "uri_pretty": "https://{username}.weebly.com"},
    {"name": "Squarespace", "uri_check": "https://{username}.squarespace.com", "m_string": "Page not found", "cat": "blog", "uri_pretty": "https://{username}.squarespace.com"},
    {"name": "Ghost", "uri_check": "https://{username}.ghost.io", "m_string": "Page not found", "cat": "blog", "uri_pretty": "https://{username}.ghost.io"},
    {"name": "Substack", "uri_check": "https://{username}.substack.com", "m_string": "Page not found", "cat": "blog", "uri_pretty": "https://{username}.substack.com"},
    {"name": "Telegraph", "uri_check": "https://telegra.ph/{username}", "m_string": "Page not found", "cat": "blog", "uri_pretty": "https://telegra.ph/{username}"},
    
    # === КРИПТОВАЛЮТЫ ===
    {"name": "Binance", "uri_check": "https://www.binance.com/en/profile/{username}", "m_string": "Page not found", "cat": "crypto", "uri_pretty": "https://www.binance.com/en/profile/{username}"},
    {"name": "Coinbase", "uri_check": "https://www.coinbase.com/{username}", "m_string": "Page not found", "cat": "crypto", "uri_pretty": "https://www.coinbase.com/{username}"},
    {"name": "Kraken", "uri_check": "https://www.kraken.com/{username}", "m_string": "Page not found", "cat": "crypto", "uri_pretty": "https://www.kraken.com/{username}"},
    {"name": "KuCoin", "uri_check": "https://www.kucoin.com/u/{username}", "m_string": "Page not found", "cat": "crypto", "uri_pretty": "https://www.kucoin.com/u/{username}"},
    {"name": "Huobi", "uri_check": "https://www.huobi.com/{username}", "m_string": "Page not found", "cat": "crypto", "uri_pretty": "https://www.huobi.com/{username}"},
    {"name": "OKX", "uri_check": "https://www.okx.com/{username}", "m_string": "Page not found", "cat": "crypto", "uri_pretty": "https://www.okx.com/{username}"},
    {"name": "Bybit", "uri_check": "https://www.bybit.com/{username}", "m_string": "Page not found", "cat": "crypto", "uri_pretty": "https://www.bybit.com/{username}"},
    {"name": "Crypto.com", "uri_check": "https://crypto.com/{username}", "m_string": "Page not found", "cat": "crypto", "uri_pretty": "https://crypto.com/{username}"},
    {"name": "Gemini", "uri_check": "https://gemini.com/{username}", "m_string": "Page not found", "cat": "crypto", "uri_pretty": "https://gemini.com/{username}"},
    {"name": "Bitstamp", "uri_check": "https://www.bitstamp.com/{username}", "m_string": "Page not found", "cat": "crypto", "uri_pretty": "https://www.bitstamp.com/{username}"},
    {"name": "OpenSea", "uri_check": "https://opensea.io/{username}", "m_string": "Page not found", "cat": "crypto", "uri_pretty": "https://opensea.io/{username}"},
    {"name": "Rarible", "uri_check": "https://rarible.com/{username}", "m_string": "Page not found", "cat": "crypto", "uri_pretty": "https://rarible.com/{username}"},
    {"name": "Foundation", "uri_check": "https://foundation.app/{username}", "m_string": "Page not found", "cat": "crypto", "uri_pretty": "https://foundation.app/{username}"},
    {"name": "SuperRare", "uri_check": "https://superrare.com/{username}", "m_string": "Page not found", "cat": "crypto", "uri_pretty": "https://superrare.com/{username}"},
    {"name": "NiftyGateway", "uri_check": "https://niftygateway.com/{username}", "m_string": "Page not found", "cat": "crypto", "uri_pretty": "https://niftygateway.com/{username}"},
    {"name": "Etherscan", "uri_check": "https://etherscan.io/address/{username}", "m_string": "Page not found", "cat": "crypto", "uri_pretty": "https://etherscan.io/address/{username}"},
    {"name": "Blockchain.com", "uri_check": "https://www.blockchain.com/explorer/addresses/btc/{username}", "m_string": "Page not found", "cat": "crypto", "uri_pretty": "https://www.blockchain.com/explorer/addresses/btc/{username}"},
    
    # === ПОКУПКИ ===
    {"name": "Amazon", "uri_check": "https://www.amazon.com/gp/profile/{username}", "m_string": "Page not found", "cat": "shopping", "uri_pretty": "https://www.amazon.com/gp/profile/{username}"},
    {"name": "eBay", "uri_check": "https://www.ebay.com/usr/{username}", "m_string": "Page not found", "cat": "shopping", "uri_pretty": "https://www.ebay.com/usr/{username}"},
    {"name": "Etsy", "uri_check": "https://www.etsy.com/people/{username}", "m_string": "Page not found", "cat": "shopping", "uri_pretty": "https://www.etsy.com/people/{username}"},
    {"name": "AliExpress", "uri_check": "https://www.aliexpress.com/user/{username}", "m_string": "Page not found", "cat": "shopping", "uri_pretty": "https://www.aliexpress.com/user/{username}"},
    {"name": "Wish", "uri_check": "https://www.wish.com/user/{username}", "m_string": "Page not found", "cat": "shopping", "uri_pretty": "https://www.wish.com/user/{username}"},
    {"name": "Mercari", "uri_check": "https://www.mercari.com/u/{username}", "m_string": "Page not found", "cat": "shopping", "uri_pretty": "https://www.mercari.com/u/{username}"},
    {"name": "Poshmark", "uri_check": "https://poshmark.com/closet/{username}", "m_string": "Page not found", "cat": "shopping", "uri_pretty": "https://poshmark.com/closet/{username}"},
    {"name": "Depop", "uri_check": "https://www.depop.com/{username}", "m_string": "Page not found", "cat": "shopping", "uri_pretty": "https://www.depop.com/{username}"},
    {"name": "Vinted", "uri_check": "https://www.vinted.com/members/{username}", "m_string": "Page not found", "cat": "shopping", "uri_pretty": "https://www.vinted.com/members/{username}"},
    {"name": "Redbubble", "uri_check": "https://www.redbubble.com/people/{username}", "m_string": "Page not found", "cat": "shopping", "uri_pretty": "https://www.redbubble.com/people/{username}"},
    {"name": "Society6", "uri_check": "https://society6.com/{username}", "m_string": "Page not found", "cat": "shopping", "uri_pretty": "https://society6.com/{username}"},
    {"name": "TeePublic", "uri_check": "https://www.teepublic.com/user/{username}", "m_string": "Page not found", "cat": "shopping", "uri_pretty": "https://www.teepublic.com/user/{username}"},
    {"name": "Zazzle", "uri_check": "https://www.zazzle.com/{username}", "m_string": "Page not found", "cat": "shopping", "uri_pretty": "https://www.zazzle.com/{username}"},
    {"name": "Spreadshirt", "uri_check": "https://www.spreadshirt.com/user/{username}", "m_string": "Page not found", "cat": "shopping", "uri_pretty": "https://www.spreadshirt.com/user/{username}"},
    {"name": "ProductHunt", "uri_check": "https://www.producthunt.com/@{username}", "m_string": "Page not found", "cat": "shopping", "uri_pretty": "https://www.producthunt.com/@{username}"},
    
    # === ПУТЕШЕСТВИЯ ===
    {"name": "TripAdvisor", "uri_check": "https://www.tripadvisor.com/members/{username}", "m_string": "Page not found", "cat": "travel", "uri_pretty": "https://www.tripadvisor.com/members/{username}"},
    {"name": "Airbnb", "uri_check": "https://www.airbnb.com/users/show/{username}", "m_string": "Page not found", "cat": "travel", "uri_pretty": "https://www.airbnb.com/users/show/{username}"},
    {"name": "Booking.com", "uri_check": "https://www.booking.com/profile/{username}", "m_string": "Page not found", "cat": "travel", "uri_pretty": "https://www.booking.com/profile/{username}"},
    {"name": "Hostelworld", "uri_check": "https://www.hostelworld.com/p/{username}", "m_string": "Page not found", "cat": "travel", "uri_pretty": "https://www.hostelworld.com/p/{username}"},
    {"name": "Couchsurfing", "uri_check": "https://www.couchsurfing.com/people/{username}", "m_string": "Page not found", "cat": "travel", "uri_pretty": "https://www.couchsurfing.com/people/{username}"},
    {"name": "Expedia", "uri_check": "https://www.expedia.com/p/{username}", "m_string": "Page not found", "cat": "travel", "uri_pretty": "https://www.expedia.com/p/{username}"},
    {"name": "Hotels.com", "uri_check": "https://www.hotels.com/p/{username}", "m_string": "Page not found", "cat": "travel", "uri_pretty": "https://www.hotels.com/p/{username}"},
    {"name": "Agoda", "uri_check": "https://www.agoda.com/profile/{username}", "m_string": "Page not found", "cat": "travel", "uri_pretty": "https://www.agoda.com/profile/{username}"},
    
    # === СПОРТ ===
    {"name": "Strava", "uri_check": "https://www.strava.com/athletes/{username}", "m_string": "Page not found", "cat": "sports", "uri_pretty": "https://www.strava.com/athletes/{username}"},
    {"name": "AllTrails", "uri_check": "https://www.alltrails.com/members/{username}", "m_string": "Page not found", "cat": "sports", "uri_pretty": "https://www.alltrails.com/members/{username}"},
    {"name": "Komoot", "uri_check": "https://www.komoot.com/user/{username}", "m_string": "Page not found", "cat": "sports", "uri_pretty": "https://www.komoot.com/user/{username}"},
    {"name": "Relive", "uri_check": "https://www.relive.cc/view/{username}", "m_string": "Page not found", "cat": "sports", "uri_pretty": "https://www.relive.cc/view/{username}"},
    {"name": "Garmin", "uri_check": "https://connect.garmin.com/modern/profile/{username}", "m_string": "Page not found", "cat": "sports", "uri_pretty": "https://connect.garmin.com/modern/profile/{username}"},
    {"name": "Suunto", "uri_check": "https://www.suunto.com/members/{username}", "m_string": "Page not found", "cat": "sports", "uri_pretty": "https://www.suunto.com/members/{username}"},
    {"name": "Polar", "uri_check": "https://flow.polar.com/profile/{username}", "m_string": "Page not found", "cat": "sports", "uri_pretty": "https://flow.polar.com/profile/{username}"},
    {"name": "Fitbit", "uri_check": "https://www.fitbit.com/profile/{username}", "m_string": "Page not found", "cat": "sports", "uri_pretty": "https://www.fitbit.com/profile/{username}"},
    
    # === КНИГИ ===
    {"name": "Goodreads", "uri_check": "https://www.goodreads.com/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://www.goodreads.com/{username}"},
    {"name": "StoryGraph", "uri_check": "https://app.thestorygraph.com/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://app.thestorygraph.com/{username}"},
    {"name": "LibraryThing", "uri_check": "https://www.librarything.com/profile/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://www.librarything.com/profile/{username}"},
    {"name": "BookBub", "uri_check": "https://www.bookbub.com/profile/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://www.bookbub.com/profile/{username}"},
    {"name": "Wattpad", "uri_check": "https://www.wattpad.com/user/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://www.wattpad.com/user/{username}"},
    {"name": "Inkitt", "uri_check": "https://www.inkitt.com/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://www.inkitt.com/{username}"},
    {"name": "RoyalRoad", "uri_check": "https://www.royalroad.com/profile/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://www.royalroad.com/profile/{username}"},
    {"name": "ScribbleHub", "uri_check": "https://www.scribblehub.com/profile/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://www.scribblehub.com/profile/{username}"},
    
    # === РАЗВЛЕЧЕНИЯ ===
    {"name": "MyAnimeList", "uri_check": "https://myanimelist.net/profile/{username}", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://myanimelist.net/profile/{username}"},
    {"name": "AniList", "uri_check": "https://anilist.co/user/{username}/", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://anilist.co/user/{username}/"},
    {"name": "Kitsu", "uri_check": "https://kitsu.io/{username}", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://kitsu.io/{username}"},
    {"name": "Letterboxd", "uri_check": "https://letterboxd.com/{username}/", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://letterboxd.com/{username}/"},
    {"name": "IMDB", "uri_check": "https://www.imdb.com/user/{username}/", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://www.imdb.com/user/{username}/"},
    {"name": "RottenTomatoes", "uri_check": "https://www.rottentomatoes.com/user/{username}", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://www.rottentomatoes.com/user/{username}"},
    {"name": "Trakt", "uri_check": "https://trakt.tv/users/{username}", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://trakt.tv/users/{username}"},
    {"name": "Simkl", "uri_check": "https://simkl.com/{username}", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://simkl.com/{username}"},
    {"name": "TVTime", "uri_check": "https://www.tvtime.com/{username}", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://www.tvtime.com/{username}"},
    {"name": "Serializd", "uri_check": "https://www.serializd.com/{username}", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://www.serializd.com/{username}"},
    
    # === ОБРАЗОВАНИЕ ===
    {"name": "Coursera", "uri_check": "https://www.coursera.org/user/{username}", "m_string": "Page not found", "cat": "education", "uri_pretty": "https://www.coursera.org/user/{username}"},
    {"name": "edX", "uri_check": "https://www.edx.org/user/{username}", "m_string": "Page not found", "cat": "education", "uri_pretty": "https://www.edx.org/user/{username}"},
    {"name": "Udemy", "uri_check": "https://www.udemy.com/user/{username}", "m_string": "Page not found", "cat": "education", "uri_pretty": "https://www.udemy.com/user/{username}"},
    {"name": "Skillshare", "uri_check": "https://www.skillshare.com/user/{username}", "m_string": "Page not found", "cat": "education", "uri_pretty": "https://www.skillshare.com/user/{username}"},
    {"name": "Domestika", "uri_check": "https://www.domestika.org/{username}", "m_string": "Page not found", "cat": "education", "uri_pretty": "https://www.domestika.org/{username}"},
    {"name": "KhanAcademy", "uri_check": "https://www.khanacademy.org/profile/{username}", "m_string": "Page not found", "cat": "education", "uri_pretty": "https://www.khanacademy.org/profile/{username}"},
    {"name": "Duolingo", "uri_check": "https://www.duolingo.com/profile/{username}", "m_string": "Page not found", "cat": "education", "uri_pretty": "https://www.duolingo.com/profile/{username}"},
    {"name": "Memrise", "uri_check": "https://www.memrise.com/user/{username}", "m_string": "Page not found", "cat": "education", "uri_pretty": "https://www.memrise.com/user/{username}"},
    {"name": "Busuu", "uri_check": "https://www.busuu.com/profile/{username}", "m_string": "Page not found", "cat": "education", "uri_pretty": "https://www.busuu.com/profile/{username}"},
    {"name": "FutureLearn", "uri_check": "https://www.futurelearn.com/profile/{username}", "m_string": "Page not found", "cat": "education", "uri_pretty": "https://www.futurelearn.com/profile/{username}"},
    
    # === РАБОТА ===
    {"name": "Upwork", "uri_check": "https://www.upwork.com/freelancers/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.upwork.com/freelancers/{username}"},
    {"name": "Fiverr", "uri_check": "https://www.fiverr.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.fiverr.com/{username}"},
    {"name": "Freelancer", "uri_check": "https://www.freelancer.com/u/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.freelancer.com/u/{username}"},
    {"name": "Toptal", "uri_check": "https://www.toptal.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.toptal.com/{username}"},
    {"name": "Guru", "uri_check": "https://www.guru.com/freelancers/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.guru.com/freelancers/{username}"},
    {"name": "PeoplePerHour", "uri_check": "https://www.peopleperhour.com/freelancer/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.peopleperhour.com/freelancer/{username}"},
    {"name": "99designs", "uri_check": "https://99designs.com/profiles/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://99designs.com/profiles/{username}"},
    {"name": "Dribbble", "uri_check": "https://dribbble.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://dribbble.com/{username}"},
    {"name": "Behance", "uri_check": "https://www.behance.net/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.behance.net/{username}"},
    {"name": "AngelList", "uri_check": "https://angel.co/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://angel.co/{username}"},
    {"name": "Crunchbase", "uri_check": "https://www.crunchbase.com/person/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.crunchbase.com/person/{username}"},
    {"name": "Xing", "uri_check": "https://www.xing.com/profile/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.xing.com/profile/{username}"},
    {"name": "Glassdoor", "uri_check": "https://www.glassdoor.com/profile/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.glassdoor.com/profile/{username}"},
    {"name": "Indeed", "uri_check": "https://www.indeed.com/profile/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.indeed.com/profile/{username}"},
    
    # === ФАЙЛОВЫЕ ХОСТИНГИ ===
    {"name": "Dropbox", "uri_check": "https://www.dropbox.com/{username}", "m_string": "Page not found", "cat": "storage", "uri_pretty": "https://www.dropbox.com/{username}"},
    {"name": "GoogleDrive", "uri_check": "https://drive.google.com/{username}", "m_string": "Page not found", "cat": "storage", "uri_pretty": "https://drive.google.com/{username}"},
    {"name": "OneDrive", "uri_check": "https://onedrive.live.com/{username}", "m_string": "Page not found", "cat": "storage", "uri_pretty": "https://onedrive.live.com/{username}"},
    {"name": "Box", "uri_check": "https://app.box.com/{username}", "m_string": "Page not found", "cat": "storage", "uri_pretty": "https://app.box.com/{username}"},
    {"name": "iCloud", "uri_check": "https://www.icloud.com/{username}", "m_string": "Page not found", "cat": "storage", "uri_pretty": "https://www.icloud.com/{username}"},
    {"name": "MEGA", "uri_check": "https://mega.nz/{username}", "m_string": "Page not found", "cat": "storage", "uri_pretty": "https://mega.nz/{username}"},
    {"name": "pCloud", "uri_check": "https://my.pcloud.com/{username}", "m_string": "Page not found", "cat": "storage", "uri_pretty": "https://my.pcloud.com/{username}"},
    {"name": "MediaFire", "uri_check": "https://www.mediafire.com/{username}", "m_string": "Page not found", "cat": "storage", "uri_pretty": "https://www.mediafire.com/{username}"},
    {"name": "4shared", "uri_check": "https://www.4shared.com/{username}", "m_string": "Page not found", "cat": "storage", "uri_pretty": "https://www.4shared.com/{username}"},
    {"name": "ZippyShare", "uri_check": "https://www.zippyshare.com/{username}", "m_string": "Page not found", "cat": "storage", "uri_pretty": "https://www.zippyshare.com/{username}"},
    
    # === ЕЩЁ БОЛЬШЕ САЙТОВ (РУССКОЯЗЫЧНЫЕ И СНГ) ===
    {"name": "OK.ru", "uri_check": "https://ok.ru/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://ok.ru/{username}"},
    {"name": "Moimir", "uri_check": "https://my.mail.ru/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://my.mail.ru/{username}"},
    {"name": "YandexZen", "uri_check": "https://zen.yandex.ru/{username}", "m_string": "Page not found", "cat": "blog", "uri_pretty": "https://zen.yandex.ru/{username}"},
    {"name": "Dzen", "uri_check": "https://dzen.ru/{username}", "m_string": "Page not found", "cat": "blog", "uri_pretty": "https://dzen.ru/{username}"},
    {"name": "Pikabu", "uri_check": "https://pikabu.ru/@{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://pikabu.ru/@{username}"},
    {"name": "Habr", "uri_check": "https://habr.com/ru/users/{username}/", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://habr.com/ru/users/{username}/"},
    {"name": "Toster", "uri_check": "https://www.toster.ru/user/{username}/answers", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://www.toster.ru/user/{username}/answers"},
    {"name": "2ch", "uri_check": "https://2ch.hk/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://2ch.hk/{username}"},
    {"name": "Leprosorium", "uri_check": "https://leprosorium.ru/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://leprosorium.ru/{username}"},
    {"name": "Kommunizm", "uri_check": "https://komunizm.ru/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://komunizm.ru/{username}"},
    {"name": "Fancy", "uri_check": "https://fancy.com/{username}", "m_string": "Page not found", "cat": "shopping", "uri_pretty": "https://fancy.com/{username}"},
    {"name": "LiveLib", "uri_check": "https://www.livelib.ru/reader/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://www.livelib.ru/reader/{username}"},
    {"name": "AuthorToday", "uri_check": "https://author.today/u/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://author.today/u/{username}"},
    {"name": "Litnet", "uri_check": "https://litnet.com/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://litnet.com/{username}"},
    {"name": "Litmarket", "uri_check": "https://litmarket.ru/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://litmarket.ru/{username}"},
    {"name": "Selfpub", "uri_check": "https://selfpub.ru/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://selfpub.ru/{username}"},
    {"name": "Litres", "uri_check": "https://www.litres.ru/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://www.litres.ru/{username}"},
    {"name": "Bookmate", "uri_check": "https://bookmate.ru/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://bookmate.ru/{username}"},
    {"name": "Kinopoisk", "uri_check": "https://www.kinopoisk.ru/user/{username}/", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://www.kinopoisk.ru/user/{username}/"},
    {"name": "Ivi", "uri_check": "https://www.ivi.ru/profile/{username}", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://www.ivi.ru/profile/{username}"},
    {"name": "Okko", "uri_check": "https://okko.tv/profile/{username}", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://okko.tv/profile/{username}"},
    {"name": "Premier", "uri_check": "https://premier.one/{username}", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://premier.one/{username}"},
    {"name": "Start", "uri_check": "https://start.ru/{username}", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://start.ru/{username}"},
    {"name": "More.tv", "uri_check": "https://more.tv/{username}", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://more.tv/{username}"},
    {"name": "Amediateka", "uri_check": "https://amediateka.ru/{username}", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://amediateka.ru/{username}"},
    {"name": "YandexMusic", "uri_check": "https://music.yandex.ru/users/{username}", "m_string": "Page not found", "cat": "music", "uri_pretty": "https://music.yandex.ru/users/{username}"},
    {"name": "VKMusic", "uri_check": "https://vk.com/artist/{username}", "m_string": "Page not found", "cat": "music", "uri_pretty": "https://vk.com/artist/{username}"},
    {"name": "Zvuk", "uri_check": "https://zvuk.com/{username}", "m_string": "Page not found", "cat": "music", "uri_pretty": "https://zvuk.com/{username}"},
    {"name": "SberZvuk", "uri_check": "https://sber-zvuk.com/{username}", "m_string": "Page not found", "cat": "music", "uri_pretty": "https://sber-zvuk.com/{username}"},
    {"name": "YandexGames", "uri_check": "https://yandex.ru/games/profile/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://yandex.ru/games/profile/{username}"},
    {"name": "VKPlay", "uri_check": "https://vkplay.ru/play/user/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://vkplay.ru/play/user/{username}"},
    {"name": "RuStore", "uri_check": "https://www.rustore.ru/catalog/app/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://www.rustore.ru/catalog/app/{username}"},
    {"name": "Ninjago", "uri_check": "https://ninjago.ru/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://ninjago.ru/{username}"},
    {"name": "Ag.ru", "uri_check": "https://www.ag.ru/profile/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://www.ag.ru/profile/{username}"},
    {"name": "Stopgame", "uri_check": "https://stopgame.ru/user/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://stopgame.ru/user/{username}"},
    {"name": "Kanobu", "uri_check": "https://www.kanobu.ru/user/{username}/", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://www.kanobu.ru/user/{username}/"},
    {"name": "DTF", "uri_check": "https://dtf.ru/{username}", "m_string": "Page not found", "cat": "gaming", "uri_pretty": "https://dtf.ru/{username}"},
    {"name": "VC.ru", "uri_check": "https://vc.ru/u/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://vc.ru/u/{username}"},
    {"name": "TJournal", "uri_check": "https://tjournal.ru/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://tjournal.ru/{username}"},
    {"name": "HabrCareer", "uri_check": "https://career.habr.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://career.habr.com/{username}"},
    {"name": "Geektimes", "uri_check": "https://geektimes.ru/{username}", "m_string": "Page not found", "cat": "coding", "uri_pretty": "https://geektimes.ru/{username}"},
    {"name": "Meer", "uri_check": "https://meer.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://meer.com/{username}"},
    {"name": "Spark", "uri_check": "https://www.spark.ru/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.spark.ru/{username}"},
    {"name": "Kwork", "uri_check": "https://kwork.ru/user/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://kwork.ru/user/{username}"},
    {"name": "FL.ru", "uri_check": "https://www.fl.ru/users/{username}/", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.fl.ru/users/{username}/"},
    {"name": "Freelance.ru", "uri_check": "https://freelance.ru/{username}/", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://freelance.ru/{username}/"},
    {"name": "Weblancer", "uri_check": "https://www.weblancer.net/users/{username}/", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.weblancer.net/users/{username}/"},
    {"name": "Freelancehunt", "uri_check": "https://freelancehunt.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://freelancehunt.com/{username}"},
    {"name": "Kabanchik", "uri_check": "https://kabanchik.ru/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://kabanchik.ru/{username}"},
    {"name": "YouDo", "uri_check": "https://youdo.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://youdo.com/{username}"},
    {"name": "Profi.ru", "uri_check": "https://www.profi.ru/profile/{username}/", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.profi.ru/profile/{username}/"},
    {"name": "Repetit.ru", "uri_check": "https://repetit.ru/{username}/", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://repetit.ru/{username}/"},
    {"name": "Ani", "uri_check": "https://ani.vg/{username}", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://ani.vg/{username}"},
    {"name": "Shikimori", "uri_check": "https://shikimori.one/users/{username}", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://shikimori.one/users/{username}"},
    {"name": "Kinoman", "uri_check": "https://kinoman.tv/{username}", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://kinoman.tv/{username}"},
    {"name": "Film.ru", "uri_check": "https://www.film.ru/person/{username}", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://www.film.ru/person/{username}"},
    {"name": "Afisha", "uri_check": "https://afisha.ru/{username}", "m_string": "Page not found", "cat": "entertainment", "uri_pretty": "https://afisha.ru/{username}"},
    {"name": "Restoclub", "uri_check": "https://www.restoclub.ru/{username}", "m_string": "Page not found", "cat": "travel", "uri_pretty": "https://www.restoclub.ru/{username}"},
    {"name": "TheVillage", "uri_check": "https://www.the-village.ru/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.the-village.ru/{username}"},
    {"name": "Wonderzine", "uri_check": "https://www.wonderzine.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.wonderzine.com/{username}"},
    {"name": "Snob", "uri_check": "https://snob.ru/profile/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://snob.ru/profile/{username}"},
    {"name": "Colta", "uri_check": "https://www.colta.ru/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.colta.ru/{username}"},
    {"name": "Polka", "uri_check": "https://polka.academy/{username}", "m_string": "Page not found", "cat": "education", "uri_pretty": "https://polka.academy/{username}"},
    {"name": "Arzamas", "uri_check": "https://arzamas.academy/{username}", "m_string": "Page not found", "cat": "education", "uri_pretty": "https://arzamas.academy/{username}"},
    {"name": "Postnauka", "uri_check": "https://postnauka.ru/{username}", "m_string": "Page not found", "cat": "education", "uri_pretty": "https://postnauka.ru/{username}"},
    {"name": "N+1", "uri_check": "https://nplus1.ru/{username}", "m_string": "Page not found", "cat": "education", "uri_pretty": "https://nplus1.ru/{username}"},
    {"name": "Indicator", "uri_check": "https://indicator.ru/{username}", "m_string": "Page not found", "cat": "education", "uri_pretty": "https://indicator.ru/{username}"},
    {"name": "Knife", "uri_check": "https://knife.media/{username}", "m_string": "Page not found", "cat": "education", "uri_pretty": "https://knife.media/{username}"},
    {"name": "Batenka", "uri_check": "https://batenka.ru/{username}", "m_string": "Page not found", "cat": "education", "uri_pretty": "https://batenka.ru/{username}"},
    {"name": "TakieDela", "uri_check": "https://takiedela.ru/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://takiedela.ru/{username}"},
    {"name": "Nastoyashchee", "uri_check": "https://www.nastoyashchee.ru/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.nastoyashchee.ru/{username}"},
    {"name": "Meduza", "uri_check": "https://meduza.io/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://meduza.io/{username}"},
    {"name": "Holod", "uri_check": "https://holod.media/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://holod.media/{username}"},
    {"name": "Kholod", "uri_check": "https://kholod.media/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://kholod.media/{username}"},
    {"name": "Baza", "uri_check": "https://baza.io/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://baza.io/{username}"},
    {"name": "Mash", "uri_check": "https://mash.ru/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://mash.ru/{username}"},
    {"name": "Lenta", "uri_check": "https://lenta.ru/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://lenta.ru/{username}"},
    {"name": "Gazeta", "uri_check": "https://www.gazeta.ru/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.gazeta.ru/{username}"},
    {"name": "Rambler", "uri_check": "https://rambler.ru/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://rambler.ru/{username}"},
    {"name": "Mail.ru", "uri_check": "https://mail.ru/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://mail.ru/{username}"},
    {"name": "Yandex", "uri_check": "https://yandex.ru/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://yandex.ru/{username}"},
    {"name": "Google", "uri_check": "https://aboutme.google.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://aboutme.google.com/{username}"},
    {"name": "Bing", "uri_check": "https://www.bing.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.bing.com/{username}"},
    {"name": "Yahoo", "uri_check": "https://yahoo.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://yahoo.com/{username}"},
    {"name": "Ask", "uri_check": "https://ask.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://ask.com/{username}"},
    {"name": "DuckDuckGo", "uri_check": "https://duckduckgo.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://duckduckgo.com/{username}"},
    {"name": "Qwant", "uri_check": "https://www.qwant.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.qwant.com/{username}"},
    {"name": "Ecosia", "uri_check": "https://www.ecosia.org/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.ecosia.org/{username}"},
    {"name": "Startpage", "uri_check": "https://www.startpage.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.startpage.com/{username}"},
    {"name": "Brave", "uri_check": "https://search.brave.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://search.brave.com/{username}"},
    {"name": "Presearch", "uri_check": "https://presearch.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://presearch.com/{username}"},
    {"name": "Metager", "uri_check": "https://metager.org/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://metager.org/{username}"},
    {"name": "Searx", "uri_check": "https://searx.me/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://searx.me/{username}"},
    {"name": "Whoogle", "uri_check": "https://whoogle.sdf.org/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://whoogle.sdf.org/{username}"},
    {"name": "Oscobo", "uri_check": "https://www.oscobo.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.oscobo.com/{username}"},
    {"name": "Gibiru", "uri_check": "https://gibiru.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://gibiru.com/{username}"},
    {"name": "Disconnect", "uri_check": "https://disconnect.search/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://disconnect.search/{username}"},
    {"name": "Ixquick", "uri_check": "https://www.ixquick.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.ixquick.com/{username}"},
    {"name": "Lycos", "uri_check": "https://www.lycos.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.lycos.com/{username}"},
    {"name": "AltaVista", "uri_check": "https://www.altavista.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.altavista.com/{username}"},
    {"name": "AllTheWeb", "uri_check": "https://www.alltheweb.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.alltheweb.com/{username}"},
    {"name": "HotBot", "uri_check": "https://www.hotbot.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.hotbot.com/{username}"},
    {"name": "InfoSpace", "uri_check": "https://www.infospace.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.infospace.com/{username}"},
    {"name": "Dogpile", "uri_check": "https://www.dogpile.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.dogpile.com/{username}"},
    {"name": "WebCrawler", "uri_check": "https://www.webcrawler.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.webcrawler.com/{username}"},
    {"name": "Excite", "uri_check": "https://www.excite.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.excite.com/{username}"},
    {"name": "LookSmart", "uri_check": "https://www.looksmart.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.looksmart.com/{username}"},
    {"name": "OpenDirectory", "uri_check": "https://www.dmoz.org/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.dmoz.org/{username}"},
    {"name": "BotW", "uri_check": "https://botw.org/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://botw.org/{username}"},
    {"name": "JoeAnt", "uri_check": "https://joeant.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://joeant.com/{username}"},
    {"name": "Gigablast", "uri_check": "https://www.gigablast.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.gigablast.com/{username}"},
    {"name": "Mojeek", "uri_check": "https://www.mojeek.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.mojeek.com/{username}"},
    {"name": "Yippy", "uri_check": "https://yippy.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://yippy.com/{username}"},
    {"name": "Zoo", "uri_check": "https://zoo.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://zoo.com/{username}"},
    {"name": "Entireweb", "uri_check": "https://www.entireweb.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.entireweb.com/{username}"},
    {"name": "ExactSeek", "uri_check": "https://www.exactseek.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.exactseek.com/{username}"},
    {"name": "E-tools", "uri_check": "https://www.e-tools.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.e-tools.com/{username}"},
    {"name": "Search", "uri_check": "https://www.search.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.search.com/{username}"},
    {"name": "A1", "uri_check": "https://www.a1.net.{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.a1.net.{username}"},
    {"name": "Alexa", "uri_check": "https://www.alexa.com/siteinfo/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.alexa.com/siteinfo/{username}"},
    {"name": "SimilarWeb", "uri_check": "https://www.similarweb.com/website/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.similarweb.com/website/{username}"},
    {"name": "Quantcast", "uri_check": "https://www.quantcast.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.quantcast.com/{username}"},
    {"name": "Compete", "uri_check": "https://www.compete.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.compete.com/{username}"},
    {"name": "SpyFu", "uri_check": "https://www.spyfu.com/overview/domain?query={username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.spyfu.com/overview/domain?query={username}"},
    {"name": "SEMrush", "uri_check": "https://www.semrush.com/info/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.semrush.com/info/{username}"},
    {"name": "Ahrefs", "uri_check": "https://ahrefs.com/site-explorer/overview/subdomains?target={username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://ahrefs.com/site-explorer/overview/subdomains?target={username}"},
    {"name": "Moz", "uri_check": "https://moz.com/domain-analysis?site={username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://moz.com/domain-analysis?site={username}"},
    {"name": "Majestic", "uri_check": "https://majestic.com/reports/link-context?ContextSite={username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://majestic.com/reports/link-context?ContextSite={username}"},
    {"name": "BuzzSumo", "uri_check": "https://app.buzzsumo.com/research?content={username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://app.buzzsumo.com/research?content={username}"},
    {"name": "SocialBlade", "uri_check": "https://socialblade.com/{platform}/user/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://socialblade.com/{platform}/user/{username}"},
    {"name": "HypeAuditor", "uri_check": "https://hypeauditor.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://hypeauditor.com/{username}"},
    {"name": "InfluencerDB", "uri_check": "https://www.influencerdb.de/influencer/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.influencerdb.de/influencer/{username}"},
    {"name": "Klear", "uri_check": "https://klear.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://klear.com/{username}"},
    {"name": "Upfluence", "uri_check": "https://www.upfluence.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.upfluence.com/{username}"},
    {"name": "AspireIQ", "uri_check": "https://www.aspireiq.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.aspireiq.com/{username}"},
    {"name": "CreatorIQ", "uri_check": "https://creatoriq.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://creatoriq.com/{username}"},
    {"name": "Traackr", "uri_check": "https://www.traackr.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.traackr.com/{username}"},
    {"name": "Onalytica", "uri_check": "https://www.onalytica.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.onalytica.com/{username}"},
    {"name": "Brandwatch", "uri_check": "https://www.brandwatch.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.brandwatch.com/{username}"},
    {"name": "Mention", "uri_check": "https://mention.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://mention.com/{username}"},
    {"name": "Talkwalker", "uri_check": "https://www.talkwalker.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.talkwalker.com/{username}"},
    {"name": "SproutSocial", "uri_check": "https://sproutsocial.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://sproutsocial.com/{username}"},
    {"name": "Hootsuite", "uri_check": "https://hootsuite.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://hootsuite.com/{username}"},
    {"name": "Buffer", "uri_check": "https://buffer.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://buffer.com/{username}"},
    {"name": "Later", "uri_check": "https://later.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://later.com/{username}"},
    {"name": "Planoly", "uri_check": "https://planoly.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://planoly.com/{username}"},
    {"name": "CoSchedule", "uri_check": "https://coschedule.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://coschedule.com/{username}"},
    {"name": "MeetEdgar", "uri_check": "https://meetedgar.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://meetedgar.com/{username}"},
    {"name": "Sendible", "uri_check": "https://www.sendible.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.sendible.com/{username}"},
    {"name": "Agorapulse", "uri_check": "https://www.agorapulse.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.agorapulse.com/{username}"},
    {"name": "Crowdfire", "uri_check": "https://www.crowdfireapp.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.crowdfireapp.com/{username}"},
    {"name": "SocialPilot", "uri_check": "https://www.socialpilot.co/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.socialpilot.co/{username}"},
    {"name": "SocialOomph", "uri_check": "https://www.socialoomph.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://www.socialoomph.com/{username}"},
    {"name": "TweetDeck", "uri_check": "https://tweetdeck.twitter.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://tweetdeck.twitter.com/{username}"},
    {"name": "Typefully", "uri_check": "https://typefully.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://typefully.com/{username}"},
    {"name": "Threader", "uri_check": "https://threader.app/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://threader.app/{username}"},
    {"name": "Tweetbot", "uri_check": "https://tapbots.com/tweetbot/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://tapbots.com/tweetbot/{username}"},
    {"name": "Twitterific", "uri_check": "https://twitterific.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://twitterific.com/{username}"},
    {"name": "Echofon", "uri_check": "https://echofon.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://echofon.com/{username}"},
    {"name": "Seesmic", "uri_check": "https://seesmic.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://seesmic.com/{username}"},
    {"name": "Twhirl", "uri_check": "https://twhirl.org/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://twhirl.org/{username}"},
    {"name": "Powertwitter", "uri_check": "https://powertwitter.net/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://powertwitter.net/{username}"},
    {"name": "Brizzly", "uri_check": "https://brizzly.com/{username}", "m_string": "Page not found", "cat": "professional", "uri_pretty": "https://brizzly.com/{username}"},
    {"name": "Plurk", "uri_check": "https://www.plurk.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.plurk.com/{username}"},
    {"name": "Identica", "uri_check": "https://identi.ca/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://identi.ca/{username}"},
    {"name": "App.net", "uri_check": "https://alpha.app.net/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://alpha.app.net/{username}"},
    {"name": "Pinboard", "uri_check": "https://pinboard.in/u:{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://pinboard.in/u:{username}"},
    {"name": "Delicious", "uri_check": "https://del.icio.us/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://del.icio.us/{username}"},
    {"name": "Digg", "uri_check": "https://digg.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://digg.com/{username}"},
    {"name": "StumbleUpon", "uri_check": "https://www.stumbleupon.com/stumbler/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.stumbleupon.com/stumbler/{username}"},
    {"name": "Mix", "uri_check": "https://mix.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://mix.com/{username}"},
    {"name": "Flipboard", "uri_check": "https://flipboard.com/@{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://flipboard.com/@{username}"},
    {"name": "Pocket", "uri_check": "https://getpocket.com/@{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://getpocket.com/@{username}"},
    {"name": "Instapaper", "uri_check": "https://www.instapaper.com/p/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.instapaper.com/p/{username}"},
    {"name": "Readability", "uri_check": "https://www.readability.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.readability.com/{username}"},
    {"name": "Scoop.it", "uri_check": "https://www.scoop.it/u/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.scoop.it/u/{username}"},
    {"name": "Pearltrees", "uri_check": "https://www.pearltrees.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.pearltrees.com/{username}"},
    {"name": "Diigo", "uri_check": "https://www.diigo.com/user/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.diigo.com/user/{username}"},
    {"name": "Fark", "uri_check": "https://www.fark.com/users/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.fark.com/users/{username}"},
    {"name": "SomethingAwful", "uri_check": "https://forums.somethingawful.com/member.php?username={username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://forums.somethingawful.com/member.php?username={username}"},
    {"name": "MetaFilter", "uri_check": "https://www.metafilter.com/user/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://www.metafilter.com/user/{username}"},
    {"name": "MetaTalk", "uri_check": "https://metatalk.metafilter.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://metatalk.metafilter.com/{username}"},
    {"name": "AskMetaFilter", "uri_check": "https://ask.metafilter.com/user/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://ask.metafilter.com/user/{username}"},
    {"name": "ProjectsMetaFilter", "uri_check": "https://projects.metafilter.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://projects.metafilter.com/{username}"},
    {"name": "MusicMetaFilter", "uri_check": "https://music.metafilter.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://music.metafilter.com/{username}"},
    {"name": "JobsMetaFilter", "uri_check": "https://jobs.metafilter.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://jobs.metafilter.com/{username}"},
    {"name": "IrlMetaFilter", "uri_check": "https://irl.metafilter.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://irl.metafilter.com/{username}"},
    {"name": "PodcastMetaFilter", "uri_check": "https://podcast.metafilter.com/{username}", "m_string": "Page not found", "cat": "social", "uri_pretty": "https://podcast.metafilter.com/{username}"},
    {"name": "FanFiction.net", "uri_check": "https://www.fanfiction.net/u/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://www.fanfiction.net/u/{username}"},
    {"name": "ArchiveOfOurOwn", "uri_check": "https://archiveofourown.org/users/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://archiveofourown.org/users/{username}"},
    {"name": "FictionPress", "uri_check": "https://www.fictionpress.com/u/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://www.fictionpress.com/u/{username}"},
    {"name": "StoriesOnline", "uri_check": "https://www.storiesonline.net/u/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://www.storiesonline.net/u/{username}"},
    {"name": "ASSTR", "uri_check": "https://www.asstr.org/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://www.asstr.org/{username}"},
    {"name": "Literotica", "uri_check": "https://www.literotica.com/authors/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://www.literotica.com/authors/{username}"},
    {"name": "Nifty", "uri_check": "https://www.nifty.org/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://www.nifty.org/{username}"},
    {"name": "TwistingCactus", "uri_check": "https://www.twistingcactus.com/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://www.twistingcactus.com/{username}"},
    {"name": "GayAuthors", "uri_check": "https://www.gayauthors.org/profile/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://www.gayauthors.org/profile/{username}"},
    {"name": "CodeBook", "uri_check": "https://codebook.io/{username}", "m_string": "Page not found", "cat": "books", "uri_pretty": "https://codebook.io/{username}"},
]
